### ISSUE TITLE
Root credential rotation endpoint is not documented

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/vault-plugin-secrets-azure#100]
Morning,

Just wanted to point out that the new endpoint for rotating the root credentials used by the secrets engine is not documented in https://www.vaultproject.io/docs/secrets/azure. It *IS* documented in the API docs at https://www.vaultproject.io/api-docs/secret/azure#rotate-root.

The endpoint was added in https://github.com/hashicorp/vault-plugin-secrets-azure/pull/64

**Comment by raymonstah** [comment]
Hey @ausfestivus, thanks for reporting this issue. The documentation has been added as part of https://github.com/hashicorp/vault/pull/19187 and will be released in the upcoming 1.14 release.
