### ISSUE TITLE
Permanently Delete SPs/Apps from AzureAD when Lease Expires

### ISSUE THREAD

**Issue by dpowley** [hashicorp/vault-plugin-secrets-azure#103]
The Vault secrets engine does not permanently delete the service principals/apps from AzureAD when leases expire. Instead, the objects are placed in a "recycle bin," and they count toward the [limit of AzureAD objects in a tenant](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#active-directory-limits) (that limit ranges from 50k to 500k objects). So after 50k-500k leases, Vault hits the limit of objects in an Azure AD and causes all create operations on the tenant to fail.

The Azure Vault secrets engine should at least provide the option to [permanently delete items](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-delete) upon expiration of leases.

**Comment by austingebauer** [comment]
Closing as fixed by #104.
