### ISSUE TITLE
How all secrets from Azure Key Vault gets updated/created in hashicorp?

### ISSUE THREAD

**Issue by sainipankaj90k** [hashicorp/vault-plugin-secrets-azure#151]
Hi,

I was following throught he guide and found it is not asking for azure key vault. 
Wondering how the secrets get added to hashicorp without this information.

Could you please help, how to configure hashicorp to get all secrets from Azure Key Vault?

TIA.

Thanks,
Pankaj

**Comment by austingebauer** [comment]
Hi, @sainipankaj90k. I'd suggest to take this question to HashiCorp's [Vault discuss](https://discuss.hashicorp.com/c/vault/30) forum. We usually reserve Github issues for bug reports or feature requests. You should be able to get some help over there. I suggest to include links to the guide you're referring to and more details on what you're trying to accomplish using Vault.
