### ISSUE TITLE
Can't configure azure role using application_object_id

### ISSUE THREAD

**Issue by marrataj** [hashicorp/vault-plugin-secrets-azure#22]
While trying to add role for azure backend using existing principal I got following error:
```
vault write azure/XXXX-XXX-XXX-XXX-XXXX/roles/my-role application_object_id=XXXX-XXXX-XXXX-XXXX-XXXXX ttl=1h
Error writing data to azure/XXXX-XXX-XXX-XXX-XXXX/roles/my-role: Error making API request.
URL: PUT https://vault-service/v1/azure/XXXX-XXX-XXX-XXX-XXXX/roles/my-role
Code: 400. Errors:
* missing Azure role definitions
```

Vault version: v0.11.1 ('8575f8fedcf8f5a6eb2b4701cb527b99574b5286')

**Comment by kalafut** [comment]
Support for using an existing service principal was added in 0.11.4: https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#0114-october-23rd-2018

**Comment by marrataj** [comment]
Thanks for fast answer I close the issue then
