### ISSUE TITLE
feature request: rotate service principal secret_id for azure/config

### ISSUE THREAD

**Issue by marcpascual** [hashicorp/vault-plugin-secrets-azure#27]
Hi!

Are there any plans to have a secret_id rotation for the service principal in the Azure secret config, similar to databases? 

regards,
Marc

**Comment by kalafut** [comment]
Not specifically scoped for Azure Secrets yet, but root credential rotation generally is a capability we'd like to expand.

**Comment by dwizzle204** [comment]
I’d also like to see some capability here to rotate those keys as security doesn’t get the warm and fuzzy having this god like account sitting there not being rotated

**Comment by tsologub** [comment]
Are there any updates on this feature request?

**Comment by reegnz** [comment]
Any plans on making this a roadmap item? Without this I feel like I have to implement a root credential rotation logic outside vault. :(
Are PR-s welcome for this feature?

**Comment by reegnz** [comment]
https://github.com/hashicorp/vault-plugin-secrets-azure/pull/64 seems to be a fix for this.

**Comment by fairclothjm** [comment]
Closed by https://github.com/hashicorp/vault-plugin-secrets-azure/pull/70
