### ISSUE TITLE
Question: Azure Role Struct Private

### ISSUE THREAD

**Issue by BrendanThompson** [hashicorp/vault-plugin-secrets-azure#28]
Is there a reason that the `azureRole` struct is private? I am extending the Vault TF provider and ideally would like to reference the `azureRole` struct to keep them inline, over writing it myself.

I can't see a reason for this struct to be private, but then again I am no `go` expert. Any clarification would be excellent!

**Comment by kalafut** [comment]
It has been a while, but if anything I'm wondering why `Role` was left exported 🙂. In general things will remain private unless there is a compelling reason to export them, to avoid broadening our API unnecessarily. In _this_ case, I do think there is a reasonable justification for `azureRole` to be exported. It relates directly to the public API so the format is essentially public anyway.

We'll take a look at changing it (and demoting `Role` which is an internal data structure that people shouldn't depend on being stable).
