### ISSUE TITLE
API Method

### ISSUE THREAD

**Issue by lightdrive** [hashicorp/vault-plugin-secrets-azure#36]
Hi,

I want to remove my need to have the vault.exe and use RestAPI's instead like i do for writing secrets etc. Is there a way for me to do this?

**Comment by kalafut** [comment]
Hi.  All of vault is accessible via API. For Azure Secrets take a look at:  https://www.vaultproject.io/api-docs/secret/azure/

**Comment by lightdrive** [comment]
Thanks, I've used the API for most of everything else I need to do but I'm unsure how to use to configure the Azure Secrets Engine. Translating the 'write' to a JSON config I can post to setup the backend for example, does that make sense?

**Comment by kalafut** [comment]
`-output-curl-string` option might help you since it translates whatever the `vault` command would do. e.g.:

```
➜  ~ vault write -output-curl-string auth/userpass/users/jim password=foo
curl -X PUT -H "X-Vault-Request: true" -H "X-Vault-Token: $(vault print token)" -d '{"password":"foo"}' http://127.0.0.1:8200/v1/auth/userpass/users/jim
```

**Comment by kalafut** [comment]
Closing as there is no defect or feature request. A better place for further usage questions is: https://discuss.hashicorp.com/c/vault
