### ISSUE TITLE
Azure resources not immediately removed on Vault role deletion

### ISSUE THREAD

**Issue by mdgreenfield** [hashicorp/vault-plugin-secrets-azure#41]
When a Vault role is deleted, any dynamic service principal or existing app passwords are not immediately removed (i.e. any active leases are not immediately revoked).

If the plugin continues to run the Azure resources will be removed when the leases expire based on the configured TTL or when the plugin is disabled.

**Comment by fairclothjm** [comment]
@mdgreenfield Hello! This functions as designed. We do not remove leases immediately after the role is deleted. We can leave this open in case there is more interest in this.

As a workaround, you can do a revoke on the prefix. See: https://developer.hashicorp.com/vault/docs/commands/lease/revoke#prefix
