### ISSUE TITLE
Generated credentials for static service principal failing 

### ISSUE THREAD

**Issue by ahackettboyle** [hashicorp/vault-plugin-secrets-azure#57]
We are seeing intermittent failures with our static service principal communicating with azure, using credentials it acquires from vault.

The error are usually something like: 
`Error listing Service Principals: autorest.DetailedError{Original:adal.tokenRefreshError{message:"adal: Refresh request failed. Status Code = '401'. Response body: {\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000215: Invalid client secret is provided.\\r\\nTrace ID: xxx \\r\\nCorrelation ID: xxxc\\r\\nTimestamp: 2021-03-04 10:22:02Z\",\"error_codes\":[7000215],\"timestamp\":\"2021-03-04 10:22:02Z\",\"trace_id\":\"xxx\",\"correlation_id\":\"xxxx\",\"error_uri\":\"https://login.microsoftonline.com/error?code=7000215\"}`

I have read the discussion in: https://github.com/hashicorp/vault-plugin-secrets-azure/issues/23 however, none of the fixes seems to apply to us. 

In our case we cannot use a dynamic sp because we need Azure AD graph API permissions. 

We are fairly sure it is not the global propagation issue as we are using the terraform data source with the validate creds function, so the SP will only start to be used once it is valid. https://registry.terraform.io/providers/hashicorp/vault/latest/docs/data-sources/azure_access_credentials

The ttl on the endpoint is 1 hour, and the number of requests to this vault endpoint is low so we are fairly sure we are not hitting the credential limit. I checked this morning after repeated failures and the SP only had about 5 tokens. 

We are using the SP for terraform runs, and in some cases we see the failure straight away, other times it is around half-way through the terraform refresh before it fails. 
In both cases the lease is still valid so I don't think it can be the TTLs, in any case the min ttl is one hour and the failures happen within 5 minutes.

Any help/suggestions would be appreciated!

**Comment by mdgreenfield** [comment]
Unfortunately, the `azure_access_credentials` resource doesn't guarantee that the credentials are fully propagated. Based on your description I'd suspect that you're still running into the global propagation issue. You may want to try increasing `num_sequential_successes` and/or `num_seconds_between_tests` a bit to see if that helps give more time for credentials to fully propagate.

**Comment by ahackettboyle** [comment]
thanks @mdgreenfield. that's the conclusion we reached as well. I have upped both which has not completely got rid of the issue but has made it rarer.
