### ISSUE TITLE
Engine documentation is out of date

### ISSUE THREAD

**Issue by ausfestivus** [hashicorp/vault-plugin-secrets-azure#79]
Morning,

Just a reminder that the Azure Secrets Engine documentation is out of date and doesn't describe how to configure the engine to use the MS Graph API instead of the (now deprecated) AAD Graph API.

https://www.vaultproject.io/docs/secrets/azure

**Comment by ausfestivus** [comment]
This is still an issue. Specifically:

The documentation for the engine on [Hashicorp Learn](https://learn.hashicorp.com/tutorials/vault/azure-secrets?in=vault/secrets-management) makes no mention of the MS Graph API permissions required.

Compare that to the permissions that are documented in the [Azure Secrets engine doco](https://www.vaultproject.io/docs/secrets/azure#ms-graph-permissions).

The two are very very different and need to be cleaned up.

**Comment by ausfestivus** [comment]
TBF, the doco for the Azure Secrets Engine and its required permissions is now very clear. Thanks to [this](https://github.com/hashicorp/vault/commit/b550a205bce3c6343cbf440e6ae61f996e99f9f8#diff-b9a52fd01ec3c81411e592e9b2d0e379afac7cda39f1cefa5c9b1110413b013e) commit.

**Comment by kalafut** [comment]
cc @yhyakuna

**Comment by yhyakuna** [comment]
The [tutorial](vault/azure-secrets) is now updated. Thank you for reporting the issue.
