### ISSUE TITLE
Support for Azure China Cloud

### ISSUE THREAD

**Issue by Harisanthosh** [hashicorp/vault-plugin-secrets-azure#86]
Greetings, working with Vault has really been a game changer as the concept of centralized secrets management and automatic secret rotation is something which we wanted to achieve across all our Kubernetes instances including the ones in China.

We ran into the following error when tried accessing the Azure Secret engine for a tenant created in China cloud
![image](https://user-images.githubusercontent.com/21079172/151192989-5b6f2249-2e79-4a02-abe9-460391b22e76.png)
When looked upon happened to note that the support is available only for Azure Global
![image](https://user-images.githubusercontent.com/21079172/151192456-67b234c4-f166-4eca-9498-46c2d06872cb.png)

It would be great to have support for different regions so that we can scale vault across all our instances globally. 

Kudos, and keep up the great work

**Comment by austingebauer** [comment]
Thanks for reporting this, @Harisanthosh! This will be fixed by https://github.com/hashicorp/vault-plugin-secrets-azure/pull/87.
